### ISSUE TITLE
GPU utilization stays at 0%

### ISSUE THREAD

**Issue by 404alya** [m87-labs/moondream#222]
When running Moondream through its CLI on Google Colab, the model is not utilizing the GPU, resulting in very slow inference times (70s per request). Despite having GPU access enabled, GPU usage remains at 0% during execution. I also don't know so much python. Here is my collab code:

`!pip install moondream`

`!curl -L -o moondream-2b-int8.mf.gz https://huggingface.co/vikhyatk/moondream2/resolve/9dddae84d54db4ac56fe37817aeaeb502ed083e2/moondream-2b-int8.mf.gz?download=true`

`!gunzip moondream-2b-int8.mf.gz`

```
!pip install aiohttp pyngrok

import torch
print("GPU available:", torch.cuda.is_available())
print("GPU device:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")

import os
import asyncio

# Set LD_LIBRARY_PATH so the system NVIDIA library
os.environ.update({'LD_LIBRARY_PATH': '/usr/lib64-nvidia'})

async def run_process(cmd):
  print('>>> starting', *cmd)
  p = await asyncio.subprocess.create_subprocess_exec(
      *cmd,
      stdout=asyncio.subprocess.PIPE,
      stderr=asyncio.subprocess.PIPE,
  )

  async def pipe(lines):
    async for line in lines:
      print(line.strip().decode('utf-8'))

  await asyncio.gather(
      pipe(p.stdout),
      pipe(p.stderr),
  )

#register an account at ngrok.com and create an authtoken and place it here
await asyncio.gather(
    run_process(['ngrok', 'config', 'add-authtoken', 'your_auth_token_here'])
)

await asyncio.gather(
    run_process(['moondream', 'serve', '--model' ,'./moondream-2b-int8.mf']),
    run_process(['curl', 'http://localhost:3475']),
    run_process(['ngrok', 'http', '--log', 'stderr', '3475', '--host-header', 'localhost:3475'])
)
```

**Comment by 404alya** [comment]
I used ollama instead of moondream cli and my problem was solved.

**Comment by betweenus** [comment]
> I used ollama instead of moondream cli and my problem was solved.

Ollama version of moondream2 is too old. New version (2025-01-09) impossible to run on GPU.
